# Generated by Django 2.2 on 2019-04-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('segundonombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidomaterno', models.CharField(max_length=100)),
                ('apelludopaterno', models.CharField(max_length=100)),
                ('telcasa', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('paginaweb', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apelludopaterno'],
            },
        ),
    ]
